# ==============================================================================
# PRODUCT: E8 Orchestrator - Guardrails & Logging
# COMPLIANCE: ISM-1511 (Log Integrity), ISM-1405 (Continuous Logging)
# DESCRIPTION: Deploys the Master Deny SCP and the Sovereign Audit Trail.
# ==============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sovereign Suite - E8 Core Guardrails and CloudTrail'

Parameters:
  RootOUID:
    Type: String
    Description: The ID of your Root Organizational Unit (e.g., r-asdf)

Resources:
  # ----------------------------------------------------------------------------
  # RESOURCE: LogArchiveBucket
  # PURPOSE: Central vault for all audit logs.
  # ----------------------------------------------------------------------------
  LogArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sovereign-audit-logs-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # ----------------------------------------------------------------------------
  # RESOURCE: SovereignCloudTrail
  # PURPOSE: Multi-region, Organization-wide audit trail.
  # ----------------------------------------------------------------------------
  SovereignCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: Sovereign-Audit-Trail
      S3BucketName: !Ref LogArchiveBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IsOrganizationTrail: true # Automatically logs all accounts in the Org
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true # Critical for ISM Log Integrity

  # ----------------------------------------------------------------------------
  # RESOURCE: E8MasterDenyPolicy (Your existing SCP)
  # ----------------------------------------------------------------------------
  E8MasterDenyPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Name: Sovereign-Master-Deny
      Type: SERVICE_CONTROL_POLICY
      Description: Blocks disabling of E8 logging (CloudTrail)
      Content:
        Version: "2012-10-17"
        Statement:
          - Sid: PreventSelfBlinding
            Effect: Deny
            Action:
              - "cloudtrail:StopLogging"
              - "cloudtrail:DeleteTrail"
              - "cloudtrail:UpdateTrail"
            Resource: "*"
      TargetIds: 
        - !Ref RootOUID
