AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sovereign Suite Core Guardrails (v4)'

Parameters:
  RootOUID:
    Type: String

Resources:
  LogArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sovereign-audit-vault-v4-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogArchiveBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub 'arn:aws:s3:::${LogArchiveBucket}'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${LogArchiveBucket}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  SovereignCloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: LogBucketPolicy
    Properties:
      TrailName: Sovereign-Audit-Trail
      S3BucketName: !Ref LogArchiveBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IsOrganizationTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true

  E8MasterDenyPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Name: Sovereign-Master-Deny
      Type: SERVICE_CONTROL_POLICY
      Description: Blocks disabling of E8 logging
      Content: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "PreventSelfBlinding",
              "Effect": "Deny",
              "Action": [
                "cloudtrail:StopLogging",
                "cloudtrail:DeleteTrail"
              ],
              "Resource": "*"
            }
          ]
        }
      TargetIds: 
        - !Ref RootOUID
